### DISCUSSION TITLE
Docker compose file

### DISCUSSION THREAD

**Discussion by DrMint** [lloesche/valheim-server-docker#107] [Show and tell]
Hi! First of all, thank you for the docker image, for those that like to self-host this is perfect.

I used docker-compose so I've written a compose file for it. Maybe someone would be interested:

```
version: '3'

services:

 valheim:
  image: lloesche/valheim-server:main
  restart: always

  volumes:
    - ./valheim-server/config:/config
    - ./valheim-server/data:/opt/valheim

  ports:
    - 2456-2458:2456-2458/udp

  environment:
   SERVER_NAME: "My server's name"
   SERVER_PORT: 2456
   WORLD_NAME: "MyWorldName"
   SERVER_PASS: "MyPassword"
   BACKUPS_MAX_AGE: 10
```
