### DISCUSSION TITLE
How to handle multiple worlds?

### DISCUSSION THREAD

**Discussion by IxsharpxI** [lloesche/valheim-server-docker#200] [Q&A]
How is it recommended to handle multiple worlds? Could you decide between them or is recommended to run one world per container?

**Comment by lloesche** [comment]
Whatever you define in `WORLD_NAME` is what the server will load. The world name corresponds directly to a set of `.db/.fwl` files in `/config/worlds/`. E.g. `WORLD_NAME=Dedicated` will load `/config/worlds/Dedicated.db`.
There is no artificial limit to the number of worlds you can create.
Whenever you start the container with a new `WORLD_NAME` the server will generate a set of new world files. Likewise if you have an existing world on your Windows/Linux Desktop you can copy the two files to the `/config/worlds/` directory, specify the name in `WORLD_NAME` without the file extension and load them into the server this way.

**Reply by IxsharpxI** [reply]
Thank you very much for your reply. So after having multiple world names such as worldA.db and worldB.db in the /config/worlds folder by either import or creating. If i'm playing in worldA with WORLD_NAME = worldA, and i wanted to switch to worldB. Then would i stop the container, change the WORLD_NAME = worldB and then start the container? Then it would use the other db?

**Reply by lloesche** [reply]
That is exactly right.

**Reply by AymanHamdoun** [reply]
@lloesche, @IxsharpxI I tried an approach that allowed me to run several containers of this image, each running its separate world at the same time and it is working fine with me

## General Idea
lets say we want to run valheim1 and valheim2 servers each with their own world. 

- we launch 2 containers with different `WORLD_NAME` environment values 
- map port 2456 in each container to a different external port _(valheim 1 maps port 3001:2456 while valheim2 uses 3003:2456)_


``` 
# in this example i kept one mapped to 2456 and the other to 3001
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS          PORTS                                                                                          NAMES
a177005a4d4e   lloesche/valheim-server         "/usr/local/sbin/boo…"   17 minutes ago   Up 17 minutes   0.0.0.0:2456-2457->2456-2457/udp, 0.0.0.0:9001->9001/tcp, 0.0.0.0:9090->80/tcp                 valheim1-container
5ba68564f3a1   lloesche/valheim-server         "/usr/local/sbin/boo…"   17 minutes ago   Up 17 minutes   0.0.0.0:9091->80/tcp, 0.0.0.0:3001->2456/udp, 0.0.0.0:3002->2457/udp, 0.0.0.0:9002->9001/tcp   valheim2-container
```

- **(if you want to access each world using SUBDOMAIN:DEFAULT_PORT)** have nginx redirect requests to each container basted on the subdomain being requested
  ```
  # /etc/nginx/sites-available/valheim1.conf
  server {
  
      server_name valheim1.domainname
      listen 2456;
  
      location / {
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass http://0.0.0.0:3001;
      }
  
  }
  
  ```
  ```
  # /etc/nginx/sites-available/valheim2.conf
  server {
  
      server_name valheim2.domainname
      listen 2456;
  
      location / {
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass http://0.0.0.0:3003;
      }
  
  }
  
  ```

  ![Valheimdrawio](https://user-images.githubusercontent.com/21179129/143766574-f98062ed-2c7b-412f-aa0b-e93c8877b0ca.png)

- when playing the game, user connects to 
    - a.domain:2456 to play in valheim1 world
    - b.domain:2456 to play in valheim2 world

**Reply by AymanHamdoun** [reply]
However, if you do not want to get a domain you can follow the first 2 steps above and disregard all the nginx related stuff and conntect to the `server IP : mapped ports`
- server:3001 for valheim1
- server:3004 for valheim2

Just make sure that the mapped ports are unblocked from your firewall, you can do so by 
``` bash
ufw allow 3001
ufw allow 3004
```

*(with the subdomain approach only port 2456 needed to be unblocked because ports 3001 & 3004 were accessed internally)*

**Reply by al13nus** [reply]
How to configure this behind Traefik? Any ideas?

**Reply by dschof41** [reply]
@AymanHamdoun are you using `docker-compose` to do that? Could you share the yaml that let's you map 3001 > 2456?

**Reply by wcdanh2** [reply]
Do not use docker's port remapping for the server ports! (if you want your server to appear in the server list.)

When the server tries to publish itself in the server list, if it does not know the actual ports used externally then it will not report correctly. This will result in your server never appearing in the server list, as well as your server never correctly displaying status if you add it to your favorites by its ip/domain.

Instead you should use the SERVER_PORT environment variable and map the port you choose (+1 for the query port) straight through in your docker-compose or docker run args.

**Reply by dschof41** [reply]
@wcdanh2 in this case I don't care about the server list stuff, but thank you for pointing out the `SERVER_PORT` method!

here's the yml that's working for me on my old ubuntu 16.04 server. The folder structure here isn't optimal but it fine for now.
```
version: "2"

services: 
  val1: 
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - $HOME/valheim-server/valheim.env
    restart: always
  val2:
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - $HOME/valheim-server/val2-server/config:/config
      - $HOME/valheim-server/val2-server/data:/opt/valheim
    ports:
      - "3456-3457:2456-2457/udp"
      - "9002:9001/tcp"
    env_file:
      - $HOME/valheim-server/val2-server/v2.env
    restart: always
```
