### DISCUSSION TITLE
Help with docker-compose.yaml file for player logging

### DISCUSSION THREAD

**Discussion by Refactron** [lloesche/valheim-server-docker#316] [Q&A] [answered]
Hello. firstly thank you very much for the work on this server. It was exactly what I wanted and I absolutely love it. 

I am trying to setup player logging to a file and eventually I will also add a player announcement to a discord web hook. I am a little new to docker-compose and to this server management so I suspect this is a simple syntax or simple concept problem. Apologies in advance for naivete. 

in my docker-compose.yaml  I have : 
```
environment:
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/<removed>/<removed>
      - DISCORD_SERVER_NAME="Snowheim"
      - VALHEIM_LOG_FILTER_CONTAINS_Spawned=Got character ZDOID from
      - ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned=cat >> /tmp/player_login_history
      - 'POST_SERVER_LISTENING_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$$(eval echo Úlfhéðnar! $$DISCORD_SERVER_NAME is up and running)\"}" "$$DISCORD_WEBHOOK"'
```

the problem I have is the _- ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned=cat >> /tmp/player_login_history_ does not work. the file is always empty.  It shows up in the _valheim-server/stderr_ log as:
```
I0412 20:40:18.134876     139 main.go:108] On log lines containing 'Got character ZDOID from' running 'cat >> /tmp/player_login_history'
I0412 20:40:18.134894     139 main.go:122] Removing empty log lines: true
I0412 20:40:18.134911     139 main.go:96] Removing log lines starting with 'src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp'
I0412 20:41:12.560729     139 main.go:241] Running hook "cat >> /tmp/player_login_history" for "04/12/2021 20:41:12: Got character ZDOID from Rando : <removed>"
```
so I can see it is firing. but still nothing is written.

Can someone help me understand how to correctly phrase this syntax or help me understand what I am doing wrong? I suspect I am merely sending the cat command as a string. I have changed the permissions of the file to be writable by any account. Any other insight? Please and thank you for the help. It's appreciated.

**Comment by lloesche** [comment, marked as answer]
Are you maybe accidentally trying to read the file on your host system instead of inside the container?

I just tried to debug your setup copy'pasting your config above but all seems to work fine.

Config
```
lukas@MACROMI:~/foobar$ cat docker-compose.yaml
version: "3"

services:
  valheim:
    image: lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - $HOME/valheim-server/valheim.env
    environment:
      - VALHEIM_LOG_FILTER_CONTAINS_Spawned=Got character ZDOID from
      - ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned=cat >> /tmp/player_login_history
    restart: always
    stop_grace_period: 2m
```

Docker console
```
valheim_1  | Apr 16 09:16:34 /supervisord: valheim-server 04/16/2021 09:16:34: VERSION check their:0.148.7  mine:0.148.7
valheim_1  | Apr 16 09:16:34 /supervisord: valheim-server 04/16/2021 09:16:34: Server: New peer connected,sending global keys
valheim_1  | Apr 16 09:16:48 /supervisord: valheim-server 04/16/2021 09:16:48: Got character ZDOID from Luu : 397833587:1
valheim_1  | Apr 16 09:16:48 /supervisord: valheim-server I0416 09:16:48.552752     138 main.go:241] Running hook "cat >> /tmp/player_login_history" for "04/16/2021 09:16:48: Got character ZDOID from Luu : 397833587:1"
```

Inside container
```
root@d659c5dc6a0d:~# cd /tmp/
root@d659c5dc6a0d:/tmp# ls -al
total 16
drwxrwxrwt 1 root root 4096 Apr 16 09:16 .
drwxr-xr-x 1 root root 4096 Apr 16 09:14 ..
drwxr-x--T 2 root root 4096 Apr 16 09:14 dumps
-rw-r--r-- 1 root root   64 Apr 16 09:16 player_login_history
root@d659c5dc6a0d:/tmp# cat player_login_history
04/16/2021 09:16:48: Got character ZDOID from Luu : 397833587:1
```
