### DISCUSSION TITLE
ValheimPlus sample config with environment variables

### DISCUSSION THREAD

**Discussion by henrysachs** [lloesche/valheim-server-docker#409] [Q&A] [answered]
Hey there, 

has anyone a Valheim plus Config created with env vars to start from? I would be happy if i didnt have to start from scratch :D

**Comment by patrickdomnick** [comment, marked as answer]
I did something in PowerShell

```ps1
function Get-IniContent ($filePath)
{
    $ini = @{}
    switch -regex -file $FilePath
    {
        "^\[(.+)\]" # Section
        {
            $section = $matches[1]
            $ini[$section] = @{}
            $CommentCount = 0
        }
        "^(;.*)$" # Comment
        {
            $value = $matches[1]
            $CommentCount = $CommentCount + 1
            $name = "Comment" + $CommentCount
            $ini[$section][$name] = $value
        }
        "(.+?)\s*=(.*)" # Key
        {
            $name,$value = $matches[1..2]
            $ini[$section][$name] = $value
        }
    }
    return $ini
}

$conf = Get-IniContent("valheim_plus.cfg")
$lines = @()
foreach ($category in $conf.Keys) {
    foreach ($key in $conf[$category].Keys) {
        $value = $conf[$category][$key]
        if ($value[0] -ne ";" -and $key[0] -ne ";") {
            $line = "VPCFG_" + $category + "_" + $key + ": " + $value
            $lines += $line
        }
    }
}
$lines | Out-File -Append valheim.yaml

```

**Reply by henrysachs** [reply]
yeah thats works quite well. We now use these environment variables as a baseline, created by one of our players:

```yaml
  VALHEIM_PLUS: true
  STATUS_HTTP: true
  STATUS_HTTP_PORT: 50801
  VPCFG_Brightness_nightBrightnessMultiplier:  0
  VPCFG_Brightness_enabled:  false
  VPCFG_Ward_wardRange:  20
  VPCFG_Ward_enabled:  false
  VPCFG_Ward_wardEnemySpawnRange:  0
  VPCFG_GameClock_textRedChannel:  248
  VPCFG_GameClock_textBlueChannel:  0
  VPCFG_GameClock_useAMPM:  false
  VPCFG_GameClock_textGreenChannel:  105
  VPCFG_GameClock_textTransparencyChannel:  255
  VPCFG_GameClock_enabled:  false
  VPCFG_GameClock_textFontSize:  34
  VPCFG_GridAlignment_align:  LeftAlt
  VPCFG_GridAlignment_enabled:  true
  VPCFG_GridAlignment_alignToggle:  F7
  VPCFG_GridAlignment_changeDefaultAlignment:  F6
  VPCFG_Furnace_coalUsedPerProduct:  1
  VPCFG_Furnace_autoDeposit:  true
  VPCFG_Furnace_autoFuel:  true
  VPCFG_Furnace_maximumCoal:  20
  VPCFG_Furnace_productionSpeed:  30
  VPCFG_Furnace_allowAllOres:  false
  VPCFG_Furnace_ignorePrivateAreaCheck:  true
  VPCFG_Furnace_autoRange:  20
  VPCFG_Furnace_maximumOre:  20
  VPCFG_Furnace_enabled:  true
  VPCFG_Bed_sleepWithoutSpawn:  true
  VPCFG_Bed_enabled:  true
  VPCFG_Bed_unclaimedBedsOnly:  false
  VPCFG_Player_cropNotifier:  true
  VPCFG_Player_deathPenaltyMultiplier:  -20
  VPCFG_Player_enabled:  true
  VPCFG_Player_skipTutorials:  false
  VPCFG_Player_baseUnarmedDamage:  70
  VPCFG_Player_restSecondsPerComfortLevel:  60
  VPCFG_Player_disableGuardianBuffAnimation:  false
  VPCFG_Player_baseMegingjordBuff:  200
  VPCFG_Player_skipIntro:  false
  VPCFG_Player_disableCameraShake:  true
  VPCFG_Player_guardianBuffDuration:  300
  VPCFG_Player_baseMaximumWeight:  400
  VPCFG_Player_baseAutoPickUpRange:  2
  VPCFG_Player_autoRepair:  true
  VPCFG_Player_iHaveArrivedOnSpawn:  true
  VPCFG_Player_autoEquipShield:  true
  VPCFG_Player_disableEncumbered:  false
  VPCFG_Player_guardianBuffCooldown:  1200
  VPCFG_Player_queueWeaponChanges:  false
  VPCFG_Player_reequipItemsAfterSwimming:  true
  VPCFG_Player_fallDamageScalePercent:  0
  VPCFG_Player_maxFallDamage:  100
  VPCFG_Armor_chests:  0
  VPCFG_Armor_enabled:  false
  VPCFG_Armor_legs:  0
  VPCFG_Armor_helmets:  0
  VPCFG_Armor_capes:  0
  VPCFG_Game_gameDifficultyHealthScale:  20
  VPCFG_Game_disablePortals:  false
  VPCFG_Game_bigPortalNames:  false
  VPCFG_Game_gameDifficultyDamageScale:  4
  VPCFG_Game_extraPlayerCountNearby:  0
  VPCFG_Game_forceConsole:  false
  VPCFG_Game_disableFog:  true
  VPCFG_Game_setFixedPlayerCountTo:  0
  VPCFG_Game_enabled:  true
  VPCFG_Game_difficultyScaleRange:  200
  VPCFG_Pickable_valuables:  0
  VPCFG_Pickable_materials:  0
  VPCFG_Pickable_edibles:  0
  VPCFG_Pickable_flowersAndIngredients:  0
  VPCFG_Pickable_surtlingCores:  0
  VPCFG_Pickable_enabled:  false
  VPCFG_PlayerProjectile_playerMaxChargeAccuracyMultiplier:  0
  VPCFG_PlayerProjectile_playerMaxChargeVelocityMultiplier:  0
  VPCFG_PlayerProjectile_enabled:  false
  VPCFG_PlayerProjectile_playerMinChargeVelocityMultiplier:  0
  VPCFG_PlayerProjectile_playerMinChargeAccuracyMultiplier:  0
  VPCFG_PlayerProjectile_enableScaleWithSkillLevel:  false
  VPCFG_Workbench_disableRoofCheck:  true
  VPCFG_Workbench_enabled:  true
  VPCFG_Workbench_workbenchAttachmentRange:  20
  VPCFG_Workbench_workbenchEnemySpawnRange:  0
  VPCFG_Workbench_workbenchRange:  100
  VPCFG_Items_droppedItemOnGroundDurationInSeconds:  3600
  VPCFG_Items_noTeleportPrevention:  false
  VPCFG_Items_baseItemWeightReduction:  -25
  VPCFG_Items_itemStackMultiplier:  0
  VPCFG_Items_enabled:  false
  VPCFG_Building_noWeatherDamage:  true
  VPCFG_Building_areaRepairRadius:  5
  VPCFG_Building_alwaysDropResources:  true
  VPCFG_Building_maximumPlacementDistance:  10
  VPCFG_Building_enableAreaRepair:  true
  VPCFG_Building_alwaysDropExcludedResources:  true
  VPCFG_Building_noMysticalForcesPreventPlacementRestriction:  false
  VPCFG_Building_pieceComfortRadius:  20
  VPCFG_Building_enabled:  true
  VPCFG_Building_noInvalidPlacementRestriction:  true
  VPCFG_Stamina_runStaminaDrain:  -50
  VPCFG_Stamina_sneakStaminaDrain:  0
  VPCFG_Stamina_jumpStaminaDrain:  0
  VPCFG_Stamina_staminaRegenDelay:  0
  VPCFG_Stamina_encumberedStaminaDrain:  0
  VPCFG_Stamina_swimStaminaDrain:  0
  VPCFG_Stamina_staminaRegen:  0
  VPCFG_Stamina_enabled:  true
  VPCFG_Stamina_dodgeStaminaUsage:  0
  VPCFG_StructuralIntegrity_disableWaterDamageToPlayerBoats:  false
  VPCFG_StructuralIntegrity_disableDamageToPlayerStructures:  true
  VPCFG_StructuralIntegrity_disableDamageToPlayerBoats:  false
  VPCFG_StructuralIntegrity_stone:  100
  VPCFG_StructuralIntegrity_wood:  100
  VPCFG_StructuralIntegrity_hardWood:  100
  VPCFG_StructuralIntegrity_disableStructuralIntegrity:  true
  VPCFG_StructuralIntegrity_iron:  100
  VPCFG_StructuralIntegrity_enabled:  true
  VPCFG_FreePlacementRotation_rotateY:  LeftAlt
  VPCFG_FreePlacementRotation_enabled:  true
  VPCFG_FreePlacementRotation_rotateX:  C
  VPCFG_FreePlacementRotation_copyRotationParallel:  F
  VPCFG_FreePlacementRotation_copyRotationPerpendicular:  G
  VPCFG_FreePlacementRotation_rotateZ:  V
  VPCFG_CraftFromChest_checkFromWorkbench:  true
  VPCFG_CraftFromChest_disableCookingStation:  true
  VPCFG_CraftFromChest_range:  20
  VPCFG_CraftFromChest_lookupInterval:  3
  VPCFG_CraftFromChest_ignorePrivateAreaCheck:  false
  VPCFG_CraftFromChest_enabled:  true
  VPCFG_Inventory_mergeWithExistingStacks:  true
  VPCFG_Inventory_playerInventoryRows:  5
  VPCFG_Inventory_enabled:  true
  VPCFG_Inventory_longboatInventoryRows:  10
  VPCFG_Inventory_cartInventoryRows:  4
  VPCFG_Inventory_personalChestColumns:  8
  VPCFG_Inventory_woodChestRows:  5
  VPCFG_Inventory_ironChestColumns:  8
  VPCFG_Inventory_ironChestRows:  10
  VPCFG_Inventory_personalChestRows:  5
  VPCFG_Inventory_longboatInventoryColumns:  4
  VPCFG_Inventory_inventoryFillTopToBottom:  false
  VPCFG_Inventory_karveInventoryColumns:  2
  VPCFG_Inventory_woodChestColumns:  8
  VPCFG_Inventory_karveInventoryRows:  10
  VPCFG_Inventory_cartInventoryColumns:  8
  VPCFG_ValheimPlus_enabled:  true
  VPCFG_ValheimPlus_mainMenuLogo:  true
  VPCFG_ValheimPlus_serverBrowserAdvertisement:  true
  VPCFG_AdvancedBuildingMode_pasteObjectRotation:  Keypad8
  VPCFG_AdvancedBuildingMode_enterAdvancedBuildingMode:  F1
  VPCFG_AdvancedBuildingMode_copyObjectRotation:  Keypad7
  VPCFG_AdvancedBuildingMode_increaseScrollSpeed:  KeypadPlus
  VPCFG_AdvancedBuildingMode_decreaseScrollSpeed:  KeypadMinus
  VPCFG_AdvancedBuildingMode_exitAdvancedBuildingMode:  F3
  VPCFG_AdvancedBuildingMode_enabled:  true
  VPCFG_MonsterProjectile_enabled:  false
  VPCFG_MonsterProjectile_monsterMaxChargeAccuracyMultiplier:  0
  VPCFG_MonsterProjectile_monsterMaxChargeVelocityMultiplier:  0
  VPCFG_Smelter_coalUsedPerProduct:  1
  VPCFG_Smelter_autoDeposit:  true
  VPCFG_Smelter_autoFuel:  true
  VPCFG_Smelter_maximumCoal:  20
  VPCFG_Smelter_productionSpeed:  30
  VPCFG_Smelter_ignorePrivateAreaCheck:  true
  VPCFG_Smelter_autoRange:  20
  VPCFG_Smelter_maximumOre:  20
  VPCFG_Smelter_enabled:  true
  VPCFG_Camera_enabled:  true
  VPCFG_Camera_cameraFOV:  65
  VPCFG_Camera_cameraBoatMaximumZoomDistance:  10
  VPCFG_Camera_cameraMaximumZoomDistance:  10
  VPCFG_Kiln_autoRange:  5
  VPCFG_Kiln_autoDeposit:  true
  VPCFG_Kiln_dontProcessFineWood:  true
  VPCFG_Kiln_autoFuel:  true
  VPCFG_Kiln_dontProcessRoundLog:  true
  VPCFG_Kiln_productionSpeed:  15
  VPCFG_Kiln_stopAutoFuelThreshold:  0
  VPCFG_Kiln_ignorePrivateAreaCheck:  true
  VPCFG_Kiln_maximumWood:  50
  VPCFG_Kiln_enabled:  true
  VPCFG_StaminaUsage_clubs:  0
  VPCFG_StaminaUsage_hammer:  0
  VPCFG_StaminaUsage_polearms:  0
  VPCFG_StaminaUsage_axes:  -25
  VPCFG_StaminaUsage_knives:  0
  VPCFG_StaminaUsage_cultivator:  0
  VPCFG_StaminaUsage_hoe:  0
  VPCFG_StaminaUsage_unarmed:  0
  VPCFG_StaminaUsage_swords:  0
  VPCFG_StaminaUsage_pickaxes:  -50
  VPCFG_StaminaUsage_enabled:  true
  VPCFG_StaminaUsage_spears:  0
  VPCFG_StaminaUsage_bows:  0
  VPCFG_StaminaUsage_blocking:  0
  VPCFG_Tameable_enabled:  true
  VPCFG_Tameable_ownerDamageOverride:  false
  VPCFG_Tameable_mortality:  0
  VPCFG_Tameable_stunRecoveryTime:  10
  VPCFG_Food_disableFoodDegradation:  true
  VPCFG_Food_enabled:  true
  VPCFG_Food_foodDurationMultiplier:  0
  VPCFG_FirstPerson_enabled:  true
  VPCFG_FirstPerson_hotkey:  F10
  VPCFG_FirstPerson_raiseFOVHotkey:  PageUp
  VPCFG_FirstPerson_lowerFOVHotkey:  PageDown
  VPCFG_FirstPerson_defaultFOV:  65.0
  VPCFG_Beehive_autoDeposit:  true
  VPCFG_Beehive_showDuration:  false
  VPCFG_Beehive_maximumHoneyPerBeehive:  10
  VPCFG_Beehive_honeyProductionSpeed:  600
  VPCFG_Beehive_autoDepositRange:  10
  VPCFG_Beehive_enabled:  true
  VPCFG_Hotkeys_rollForwards:  F9
  VPCFG_Hotkeys_enabled:  false
  VPCFG_Hotkeys_rollBackwards:  F10
  VPCFG_Windmill_maximumBarley:  50
  VPCFG_Windmill_ignoreWindIntensity:  true
  VPCFG_Windmill_autoDeposit:  true
  VPCFG_Windmill_autoFuel:  true
  VPCFG_Windmill_productionSpeed:  10
  VPCFG_Windmill_ignorePrivateAreaCheck:  true
  VPCFG_Windmill_autoRange:  5
  VPCFG_Windmill_enabled:  true
  VPCFG_Experience_spears:  30
  VPCFG_Experience_axes:  30
  VPCFG_Experience_jump:  50
  VPCFG_Experience_enabled:  true
  VPCFG_Experience_clubs:  30
  VPCFG_Experience_frostMagic:  50
  VPCFG_Experience_blocking:  30
  VPCFG_Experience_bows:  30
  VPCFG_Experience_sneak:  50
  VPCFG_Experience_knives:  30
  VPCFG_Experience_run:  50
  VPCFG_Experience_polearms:  30
  VPCFG_Experience_pickaxes:  30
  VPCFG_Experience_swords:  30
  VPCFG_Experience_unarmed:  50
  VPCFG_Experience_fireMagic:  50
  VPCFG_Experience_swim:  50
  VPCFG_Experience_woodCutting:  25
  VPCFG_Shields_blockRating:  0
  VPCFG_Shields_enabled:  false
  VPCFG_Gathering_chitin:  50
  VPCFG_Gathering_copperOre:  50
  VPCFG_Gathering_fineWood:  0
  VPCFG_Gathering_dropChance:  100
  VPCFG_Gathering_tinOre:  50
  VPCFG_Gathering_wood:  0
  VPCFG_Gathering_silverOre:  50
  VPCFG_Gathering_coreWood:  0
  VPCFG_Gathering_stone:  0
  VPCFG_Gathering_elderBark:  0
  VPCFG_Gathering_ironScrap:  50
  VPCFG_Gathering_enabled:  true
  VPCFG_Fermenter_fermenterItemsProduced:  6
  VPCFG_Fermenter_autoDeposit:  true
  VPCFG_Fermenter_showDuration:  true
  VPCFG_Fermenter_autoFuel:  true
  VPCFG_Fermenter_fermenterDuration:  1200
  VPCFG_Fermenter_ignorePrivateAreaCheck:  true
  VPCFG_Fermenter_autoRange:  10
  VPCFG_Fermenter_enabled:  true
  VPCFG_SpinningWheel_autoDeposit:  true
  VPCFG_SpinningWheel_autoFuel:  true
  VPCFG_SpinningWheel_productionSpeed:  30
  VPCFG_SpinningWheel_ignorePrivateAreaCheck:  true
  VPCFG_SpinningWheel_autoRange:  10
  VPCFG_SpinningWheel_maximumFlax:  50
  VPCFG_SpinningWheel_enabled:  true
  VPCFG_Wagon_enabled:  false
  VPCFG_Wagon_wagonBaseMass:  20
  VPCFG_Wagon_wagonExtraMassFromItems:  0
  VPCFG_FireSource_autoFuel:  false
  VPCFG_FireSource_fires:  true
  VPCFG_FireSource_ignorePrivateAreaCheck:  true
  VPCFG_FireSource_autoRange:  10
  VPCFG_FireSource_enabled:  true
  VPCFG_FireSource_torches:  true
  VPCFG_AdvancedEditingMode_enterAdvancedEditingMode:  Keypad0
  VPCFG_AdvancedEditingMode_pasteObjectRotation:  Keypad8
  VPCFG_AdvancedEditingMode_confirmPlacementOfAdvancedEditingMode:  KeypadEnter
  VPCFG_AdvancedEditingMode_abortAndExitAdvancedEditingMode:  F8
  VPCFG_AdvancedEditingMode_copyObjectRotation:  Keypad7
  VPCFG_AdvancedEditingMode_increaseScrollSpeed:  KeypadPlus
  VPCFG_AdvancedEditingMode_resetAdvancedEditingMode:  F7
  VPCFG_AdvancedEditingMode_decreaseScrollSpeed:  KeypadMinus
  VPCFG_AdvancedEditingMode_enabled:  false
  VPCFG_Server_disableServerPassword:  false
  VPCFG_Server_maxPlayers:  10
  VPCFG_Server_serverSyncHotkeys:  true
  VPCFG_Server_enforceMod:  true
  VPCFG_Server_serverSyncsConfig:  true
  VPCFG_Server_enabled:  true
  VPCFG_Durability_pickaxes:  0
  VPCFG_Durability_weapons:  0
  VPCFG_Durability_hammer:  0
  VPCFG_Durability_axes:  0
  VPCFG_Durability_cultivator:  0
  VPCFG_Durability_hoe:  0
  VPCFG_Durability_shields:  0
  VPCFG_Durability_torch:  0
  VPCFG_Durability_bows:  0
  VPCFG_Durability_enabled:  false
  VPCFG_Durability_armor:  0
  VPCFG_Map_preventPlayerFromTurningOffPublicPosition:  true
  VPCFG_Map_exploreRadius:  150
  VPCFG_Map_shareAllPins:  false
  VPCFG_Map_shareMapProgression:  true
  VPCFG_Map_enabled:  true
  VPCFG_Map_displayCartsAndBoats:  true
  VPCFG_Map_shareablePins:  true
  VPCFG_Hud_removeDamageFlash:  false
  VPCFG_Hud_displayBowAmmoCounts:  0
  VPCFG_Hud_enabled:  false
  VPCFG_Hud_experienceGainedNotifications:  false
  VPCFG_Hud_showRequiredItems:  false
```
