### DISCUSSION TITLE
Adding ValheimPlus to existing server?

### DISCUSSION THREAD

**Discussion by iheijoushin** [lloesche/valheim-server-docker#440] [Q&A]
lloesche you have done a truly amazing amount of work building, maintaining, and documenting this docker image! Thank you!

I have a basic Docker Container set up on my QNAP NAS and have started a game with some friends. We're finding we would really like some QOL features offered by ValheimPlus. Which brings me to my question: can we activate Valheim Plus on an existing server?

I reviewed your documentation and attempted to add `VALHEIM_PLUS=true` to the `valheim.env` file that is referenced in the Docker Compose file under `env_file`. Then restarted the server but there's no ValheimPlus version listed on the game's main menu so I do not think I succeeded. I searched discussions and looked at the documentation a second time and must be missing something.

Here is my Docker Compose:
```
version: "3"

services: 
  valheim: 
    image: lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - /share/CACHEDEV1_DATA/Container/Valheim/config:/config
      - /share/CACHEDEV1_DATA/Container/Valheim/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - /share/CACHEDEV1_DATA/Container/Valheim/valheim.env
    restart: always
    stop_grace_period: 2m
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 4gb

```
And my valheim.env file:
```
SERVER_NAME=*******
WORLD_NAME=*******
SERVER_PASS=*******
SERVER_PUBLIC=true
VALHEIM_PLUS=true
```

Any help is sincerely appreciated and thank you again.
