### DISCUSSION TITLE
Where is the valheim.env file

### DISCUSSION THREAD

**Discussion by Jmag103** [lloesche/valheim-server-docker#461] [Q&A] [answered]
So I'm sort of a novice to this, but I'm trying to get the discord webhooks setup for my server, but I can't seem to find the valheim.env file. Would I need to create it? If so where is it supposed to be?

**Comment by drpcken** [comment, marked as answer]
It should be in the root folder the docker container lives.  Same place as your `docker-compose.yaml` if you created the container using docker-compose.  

You can actually specify where you want it in your `docker-compose.yaml`:

```yaml
version: "3"

services:
   valheim:
      image: ...
      volumes:
         - ...
      ports:
         - ...
      env_file:
         - ./valheim.env
      ...
```

The above config will put it in the root server folder along with your `docker-compose.yaml`.

**Reply by Jmag103** [reply]
Yea its not in the root. I just created it in $home/valheim-server/valheim.env hoping that would work, but I'm not sure yet.

**Reply by drpcken** [reply]
What folder does your server reside in?

![image](https://user-images.githubusercontent.com/435835/156428876-f02cede5-6459-4b69-80e2-ded505f1152b.png)

**Reply by Jmag103** [reply]
$home/usr/local/bin

**Reply by Jmag103** [reply]
I think I got mixed up. I'm running docker on windows so I have the container mounted to a docker/valheim-server/config and docker/valheim-server/data. Does the valheim.env need to be there or in the actual root of the container?

**Reply by drpcken** [reply]
the `valheim.env` file should be in `docker/valheim-server/` (I'm pretty sure that is where it looks for it by default).  Remember when you create or edit the `valheim.env` file you have to rebuild your container with `docker-compose up -d` for the changes to take effect.

**Reply by Jmag103** [reply]
Ah I just started using docker 2 days ago, haven't used docker-compose yet. Would I still need to do that if I didn't create the container with docker-compose? Or is there another way?

**Reply by drpcken** [reply]
I’m more familiar with docker-compose for building containers. Do you have a docker file or docker-compose.yaml  (or both)?  How did you originally build this contsiner?

**Reply by Jmag103** [reply]
just followed the guide 
$ docker run -d \
    --name valheim-server \
    --cap-add=sys_nice \
    --stop-timeout 120 \
    -p 2456-2457:2456-2457/udp \
    -v $HOME/valheim-server/config:/config \
    -v $HOME/valheim-server/data:/opt/valheim \
    -e SERVER_NAME="My Server" \
    -e WORLD_NAME="Neotopia" \
    -e SERVER_PASS="secret" \
    ghcr.io/lloesche/valheim-server

**Reply by Jmag103** [reply]
I have no attachments to this container so i'm just going to go play around with docker-compose

**Reply by drpcken** [reply]
If you were able to build a container manually the way you did, you should have no problems using `docker-compose`.  In my opinion it is a much more efficient way to create and maintain a docker container.  [Here are the steps](https://github.com/lloesche/valheim-server-docker#deploying-with-docker-compose) I followed and it was relatively painless.   These steps assume you're using linux, but it boils down to creating the valheim.env and `docker-compose.yaml` file, putting it in a `/valheim-server/` folder and running `docker-compose -d up`.

I'll be glad to help you build the env and yaml file if you'd like.

**Reply by Jmag103** [reply]
I'm running on windows so I don't think those steps work for me.

**Reply by drpcken** [reply]
Those exact steps/commands will not carry over to windows, but the steps I would take on windows:

1.  Create a folder structure for the server container
     
    ```
    path/valheim-server
     |__config
     |__data
    ```
    
2.  Create your `valheim.env` file.  [There are a lot of options](https://github.com/lloesche/valheim-server-docker#environment-variables), but basic env variables needed would be:

     ```env
     SERVER_NAME=name
     WORLD_NAME=world
     SERVER_PUBLIC=true/false
     SERVER_PASS=
     ```
3. Create your `docker-compose.yaml` file.  This is used to build the container. Mine looks similar to this:

```yaml
version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - ./config:/config
      - ./data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - ./valheim.env
    restart: always
    stop_grace_period: 2m
```

4.  Drop both `valheim.env` and `docker-compose.yaml` into your root folder you created in step 1.  `path/valheim-server`
5. Open command line/powershell and go to that folder and type `docker-compose -d up`.  This will build the image and start the server.  When you need to make a change to the env file, run that command again to rebuild the image (your volumes will remain intact).
