### DISCUSSION TITLE
Can't seem to figure out backups

### DISCUSSION THREAD

**Discussion by generalrap** [lloesche/valheim-server-docker#602] [Q&A]
I can't seem to figure out automatic backups. In my environment file, I have the following defined, which should zip a backup and add it to the backups directory every 5 minutes, regardless if players are on the server or not, and hold an unlimited amount of backups until they reach 7 days of age. (I get that this is overkill; I'm just trying to troubleshoot, and will move things to a 1 hour time frame afterward)
```
BACKUPS=true
BACKUPS_CRON="*/5 * * * *"
BACKUPS_DIRECTORY=/config/backups
BACKUPS_MAX_AGE=7
BACKUPS_MAX_COUNT=0
BACKUPS_IF_IDLE=true
BACKUPS_IDLE_GRACE_PERIOD=0
PERMISSIONS_UMASK=022
```
However, it does not seem to work fully. The backups subdirectory has been created in config, and a backup file is generated every time the server is stood up, whether manually or automatically. But after that initial file, nothing else happens. Am I missing something? I feel like this should be pretty straightforward.

For additional context, here's my docker-compose.yaml:
```
version: "3"

services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - /srv/valheim/server_files/config:/config
      - /srv/valheim/server_files/opt:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - /srv/valheim/server_files/docker/docker_environment_variables.env
    restart: always
    stop_grace_period: 2m
```
