### DISCUSSION TITLE
Unable to connect to container

### DISCUSSION THREAD

**Discussion by russellaa** [lloesche/valheim-server-docker#675] [Q&A]
I am unable to connect to the container I have attempted to launched. I have enabled the both the status page and the supervisor page to simply see if I can establish a connection and it cannot. I cannot make a connection from the game locally via IP:Port (example: 192.168.1.254:2456). It is not showing up when I search locally from Steam either.

I am trying to run this on a Synology DS1621+ with upgraded RAM. I am also using Portainer to launch my containers. I have included the docker file.

```yaml
version: "3.8"
  services:
    valheim:
      container_name: valheim
      restart: always
      privileged: true    
      network_mode: host
      cap_add: 
          - SYS_ADMIN    
      volumes:
          - '/volume1/valheim/config:/config'
          - '/volume1/valheim/opt/valheim:/opt/valheim'
      environment:
          - TZ=America/Los_Angeles
          - SERVER_NAME='Home Server'
          - WORLD_NAME='World1'
          - DNS_1=8.8.8.8
          - DNS_2=8.8.8.4
          #- SERVER_PORT=2456
          - SERVER_PASS='Password'
          - SERVER_PUBLIC='true'
          - BACKUPS_MAX_AGE=14
          - STATUS_HTTP='true'
          #- STATUS_HTTP_PORT=9780
          - SUPERVISOR_HTTP='true'
          #- SUPERVISOR_PORT=9797
          - SUPERVISOR_HTTP_USER='admin'
          - SUPERVISOR_HTTP_PASS='Password'
          #- SERVER_ARGS='-crossplay'
      ports:
          - '9797:9001/tcp' 
          - '9780:80/tcp'
          - '2456:2456/udp'
          - '2457:2457/udp'
          - '2458:2458/udp'
      image: ghcr.io/lloesche/valheim-server:latest 
```

_One thing to note is I do have HSTS enabled on my Synology. I do need to keep that enabled. I also have a DNS rewrite rules and have set up my Synology to act as a reverse gateway that redirects custom URL's to a back end container/port. That work for other containers but does not work for this one._
