### ISSUE TITLE
server version

### ISSUE THREAD

**Issue by Mickroz** [lloesche/valheim-server-docker#116]
Hi, i cannot connect to the server because the server version: has incompatible version, mine:0.146.11@0.9 remote 0.146.11
There is no update for valheim, so im guessing this is beta version?

im deploying through stack:
```
---
version: "2"
services:
  valheim-server:
    image: lloesche/valheim-server
    container_name: valheim-server
    network_mode: host
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Amsterdam
      - SERVER_NAME=Server Name
      - WORLD_NAME=worldname
      - SERVER_PASS=secret
      - VALHEIM_PLUS=true
    ports:
      - 2456-2458:2456-2458/udp
    volumes:
      - /volume1/docker/valheim/config:/config
      - /volume1/docker/valheim/data:/opt/valheim
    restart: unless-stopped
```
