### ISSUE TITLE
Game server doesn't stay connected

### ISSUE THREAD

**Issue by DailytheNoob** [lloesche/valheim-server-docker#141]
I am able to connect to the server on the local network, but outside connections aren't staying connected.

Here's my NAT:
![image](https://user-images.githubusercontent.com/18452976/109691035-9f94eb80-7b4c-11eb-9a6e-2696b7b20464.png)

I have this running on a CentOS 7 VM on a Ubuntu 20.04 host. Here's my `docker-compose.yaml` that's based on the run command because [the version indicated on the file in this repo doesn't exist yet](https://github.com/lloesche/valheim-server-docker/blob/7835f53aae8e54e604e159642b5a683563bc45d0/docker-compose.yaml#L1).
 
```
version: '3.3'
services:
    valheim-server:
        container_name: valheim-server
        ports:
            - '2455-2458:2455-2458/udp'
        volumes:
            - '/valheim/config:/config'
            - '/valheim/data:/opt/valheim'
        environment:
            - SERVER_NAME=Daily Server
            - WORLD_NAME=World name
            - SERVER_PASS=secret
            - BACKUPS=true
            - BACKUPS_CRON=*3***
            - BACKUPS_MAX_AGE=3
            - SERVER_PUBLIC=true
        image: lloesche/valheim-server
        restart: unless-stopped
```

Here's the error:
![image](https://user-images.githubusercontent.com/18452976/109693893-cb65a080-7b4f-11eb-8866-8d87515cb9d0.png)

The timezone in the docker container is also UTC, could that be the issue?

**Comment by InB4DevOps** [comment]
Maybe also add 2455 to the compose yml...

**Comment by DailytheNoob** [comment]
Sadly that didn't change anything

**Comment by lloesche** [comment]
@DailytheNoob Valheim doesn't use TCP; UDP only. What's your UDP conntrack timeouts look like? I.e. `net.netfilter.nf_conntrack_udp_timeout` and `net.netfilter.nf_conntrack_udp_timeout_stream`. I'd try setting to something like 20 minutes (1200) and see if it changes anything.
My thinking is, since it is working internally but not externally I would assume the issue is likely with whatever gateway device is in between.

Also out of curiosity, why running in a CentOS VM on an Ubuntu host? Like why not just run the container on the Ubuntu host directly? 🤔

**Comment by DailytheNoob** [comment]
Sadly I am still getting the same error messages after restarting the container and docker.
https://asciinema.org/a/396181

Why the VM on the Ubuntu Host? Cause I have a few other OSes running in there, like VyOS, and I don't want to inevitably bork the connection I'm using to control the OS, so I've got the second interface bridged and that's what all the VMs can use.

**Comment by lloesche** [comment]
Oh, this is your outgoing connection, from the game server to Steam we're talking about? I thought the incoming connection from your game client was getting disconnected.

In that case I don't really know what the issue could be. The guys in #140 seem to have found a workaround by starting the container with host networking. But there I'm now unclear on whether that fixed incoming or outgoing connections (or potentially both).

**Comment by DailytheNoob** [comment]
The incoming connection doesn't work either. I'll try the host networking option and will get back in ~1 hour

**Comment by WanielDeiss** [comment]
i have still the same problem.

i am hosting this on a digital ocean droplet, my docker-compose.yml file looks like:

```yml
version: "3.9"
services:
  valheim:
    image: lloesche/valheim-server
    restart: always
    network_mode: host
    volumes:
      - /root/valheim-server/config:/config
      - /root/valheim-server/data:/opt/valheim
    ports:
      - "2455-2458:2455-2458/udp"
    environment:
      - SERVER_NAME=Landshut
      - SERVER_PASS=secret
      - SERVER_PUBLIC=1
      - WORLD_NAME=FooBar
 ```
