### ISSUE TITLE
Suggestion: Don't really need systemd container

### ISSUE THREAD

**Issue by romainchassaigne** [lloesche/valheim-server-docker#159]
Hello,

You don't really need systemd for the Docker deployment. Instead you should use restart=always it is a better way to keep the server alive even if the container crash.

Add this to your docker command:
```
docker run -d \
    --name valheim-server \
    -p 2456-2458:2456-2458/udp \
    -v $HOME/valheim-server/config:/config \
    -v $HOME/valheim-server/data:/opt/valheim \
    -e SERVER_NAME="My Server" \
    -e WORLD_NAME=Neotopia \
    -e SERVER_PASS=secret \
    --restart always
    lloesche/valheim-server
```

You could also add docker-compose this way:

```yaml
version: '3'

services:
  valheim-server:
    image: lloesche/valheim-server
    ports:
       - 2465-2458:2465-2458/udp
    volumes:
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    environment:
      - SERVER_NAME=My Server
      - WORLD_NAME=Neotopia
      - SERVER_PASS=secret
    restart: always
```
And then deploy with `docker-compose up -d`
