### ISSUE TITLE
Question - (DEBUG) Valheim Server is not yet downloaded - waiting

### ISSUE THREAD

**Issue by chrsolr** [lloesche/valheim-server-docker#184]
I use Docker for Mac and I keep getting "(DEBUG) Valheim Server is not yet downloaded - waiting" message on the logs.

`docker-compose.yaml`:
```
version: "3"

services: 
  valheim: 
    image: lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - $HOME/Documents/valheim/valheim-server/config:/config
      - $HOME/Documents/valheim/valheim-server/data:/opt/valheim
    ports: 
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - $HOME/Documents/valheim/valheim-server/valheim.env
    restart: always
```
and `valheim.env`:
```
SERVER_NAME="Z8OTester"
WORLD_NAME=WORLD
SERVER_PASS=secret
SERVER_PUBLIC=true
```
