### ISSUE TITLE
Server does not work with ValheimPlus and no password

### ISSUE THREAD

**Issue by Behoston** [lloesche/valheim-server-docker#219]
Server still asking for a password (on both, Valheim Plus client and vanilla). On Vanilla returns wrong password, on VP it show incomaptible version (like a vanilla server for VP clients).

```yaml
version: '3'
services:
  server:
    image: 'lloesche/valheim-server'
    ports:
      - 2356-2357:2356-2357/udp
      - 9001:9001/tcp
      - 9002:9002/tcp
    volumes:
      - ./Valheim:/config
      - ./data:/opt/valheim
    environment:
      - WORLD_NAME=test1
      - SERVER_NAME='***** ***'
      - SERVER_PASS=''
      - SERVER_PUBLIC=false
      - SERVER_PORT=2356
      - SUPERVISOR_HTTP=true
      - SUPERVISOR_HTTP_USER=behoston
      - SUPERVISOR_HTTP_PASS=dupa123
      - STATUS_HTTP=true
      - STATUS_HTTP_PORT=9002
      - VALHEIM_PLUS=true
      - VPCFG_Server_enabled=true
      - VPCFG_Server_enforceMod=false
      - VPCFG_Server_disableServerPassword=true
      - DEBUG_START_FRESH=true
    cap_add:
      - sys_nice
    stop_grace_period: 2m
```

```bash
cat ./Valheim/valheimplus/valheim_plus.cfg
```
```ini
[AdvancedBuildingMode]
enabled=true
enterAdvancedBuildingMode=F1
exitAdvancedBuildingMode=F3
copyObjectRotation=Keypad7
pasteObjectRotation=Keypad8

[...]

[Server]
enabled=true
maxPlayers=10
disableServerPassword=true
enforceMod=false
serverSyncsConfig=true
dataRate=60

[...]
```
