### ISSUE TITLE
Discord Message & Hook Environment Variables not enumerated properly with docker stack deploy

### ISSUE THREAD

**Issue by jcolley** [lloesche/valheim-server-docker#227]
First off, thanks for creating this image and providing the _awesome documentation_ for it.
The example `docker-compose.yml` shows environment variables used for both Discord Messages and Discord Webhooks, however when starting the service, it seems the hooks are enumerated before the Messages.

Things to note about my experience with this image / environment:
- Everything else is working great! Only the Discord hook environment variables are giving me a hard time
- I'm using a 5-node Docker Swarm

Here is my `docker-compose.yml`:
```yaml
version: "3.8"
services:
  valheim:
    image: lloesche/valheim-server:latest
    cap_add:
      - sys_nice
    volumes:
      - /mnt/storage1.noc2/docker/dev/vanirsdisease.boxspawn.com/data:/opt/valheim
      - /mnt/storage1.noc2/docker/dev/vanirsdisease.boxspawn.com/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SERVER_NAME: "SomeServerName"
      SERVER_PORT: "2456"
      WORLD_NAME: "Dedicated"
      SERVER_PASS: "nothtepassword"
      SERVER_PUBLIC: "true"
      STATUS_HTTP: "true"
      SUPERVISOR_HTTP: "true"
      SUPERVISOR_HTTP_USER: "admin"
      SUPERVISOR_HTTP_PASS: "notthepassword"
     
      DISCORD_POST_START: "__Valheim Server is now online.__\nJoin @ valheim.spiffydomain.com \nPassword: **nothtepassword**"
      DISCORD_PRE_RESTART: "**Restarting** Valheim Server in one minute!"
      DISCORD_POST_RESTART: "Valheim Server restart complete."
      DISCORD_PRE_UPDATE: "Checking for Valheim Server updates, since nobody is on..."
      DISCORD_PRE_SERVER_SHUTDOWN: "Valheim Server has been shutdown; most likely for maintenance."
      DISCORD_WEBHOOK: "https://discord.com/api/webhooks/12345678/2134234234_reallylongapihook"

      POST_START_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_POST_START\"}" "$DISCORD_WEBHOOK"'
      PRE_RESTART_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_PRE_RESTART\"}" "$DISCORD_WEBHOOK" && sleep 60'
      POST_RESTART_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_POST_RESTART\"}" "$DISCORD_WEBHOOK"'
      PRE_UPDATE_CHECK_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_PRE_UPDATE\"}" "$DISCORD_WEBHOOK"'
      PRE_SERVER_SHUTDOWN_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_PRE_SERVER_SHUTDOWN\"}" "$DISCORD_WEBHOOK"'
    networks:
      - my-public-internet-facing-ingress-network

networks:
  my-public-internet-facing-ingress-network:
    external: true
```
Server logs show the webhook output as follows:
```bash
2021-03-14 17:30:06 [44] (INFO) Running pre update check hook: curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"\"}" ""
curl: (3) URL using bad/illegal format or missing URL
```
Obviously, it's missing the $DISCORD_* environment variable values.
When I exec into the running server container and echo the values of the environment variables I see that the $DISCORD_* environment variables appear to be set correct, but their values are just omitted from the hook variables:
```bash
root@edd8d37c5f88:/# echo $DISCORD_POST_RESTART
Valheim Server restart complete.
root@edd8d37c5f88:/# echo $POST_RESTART_HOOK
curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"\"}" ""
```
While I could always rebuild and embed the environment variables into the image so that they absolutely exist prior to a container instance being created, having to rebuild the image every time I want to add/remove/update messages seems a bit overkill for something this simple - especially since I'm going to need the ability to update these messages from a web-interface at some point.

I feel like I'm overlooking something really simple and just need another pair of eyes to point it out. I hope it's that simple :)
See anything obvious?
