### ISSUE TITLE
problems running on azure; 15min startup for unlisted instance

### ISSUE THREAD

**Issue by Groostav** [lloesche/valheim-server-docker#26]
Thanks for the docker container here! I played a bunch on a friends hosted machine, he had to go but I wanted to keep playing, this got me thinking it would be nice to host our game on a dedicated machine.

So I'm trying to get it running in an azure container. My config:

```yaml
name: valheim-group 
apiVersion: '2019-12-01'
properties: 
  osType: Linux
  restartPolicy: Never
  
  containers:
  - name: valheim
    properties: 
      image: lloesche/valheim-server
      ports: 
      - protocol: udp
        port: 2456
      - protocol: udp
        port: 2457
      - protocol: udp
        port: 2458
      - port: 27015 
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 8.0
      volumeMounts:
      - mountPath: /config
        name: valheim-volume
      environmentVariables:
      - name: SERVER_NAME
        value: grooserver
      - name: WORLD_NAME
        value: groorld
      - name: SERVER_PASS
        value: xxxxxxxx

  ipAddress:
    type: Public
    ports:
    - protocol: udp
      port: 2456
    - protocol: udp
      port: 2457
    - protocol: udp
      port: 2458
    - port: 27015 
    dnsNameLabel: groostav-valheim
  
  volumes:
  - name: valheim-volume
    azureFile:
      sharename: groostav-valheim-fs
      storageAccountName: empoweropsstorage
      storageAccountKey: l5xxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==
```

an `azure container create` with the above file yields some fairly promising output:

```
2021-02-15 07:30:04,517 INFO Set uid to user 0 succeeded
2021-02-15 07:30:04,525 INFO RPC interface 'supervisor' initialized
2021-02-15 07:30:04,525 INFO supervisord started with pid 1
2021-02-15 07:30:05,528 INFO spawned: 'valheim-updater' with pid 10
2021-02-15 07:30:05,530 INFO spawned: 'valheim-backup' with pid 11
Running Valheim Server updater as user root uid 0
Backing up Valheim server worlds to /config/backups/worlds-20210215-073005.zip
Updating/Validating Valheim Server
  adding: worlds/ (stored 0%)
  adding: worlds/groorld.db (deflated 51%)
  adding: worlds/groorld.fwl (deflated 5%)
Removing backups older than 3 days
Waiting 3600 seconds before next backup run
2021-02-15 07:30:06,852 INFO success: valheim-updater entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-15 07:30:06,852 INFO success: valheim-backup entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
...
Success! App '896660' fully installed.
>f+++++++++ LinuxPlayer_s.debug
...
Valheim Server was updated - restarting
2021-02-15 07:31:39,588 INFO spawned: 'valheim-server' with pid 78
Running Valheim Server
Found path: /opt/valheim/valheim_server.x86_64
Mono path[0] = '/opt/valheim/valheim_server_Data/Managed'
Mono config path = '/opt/valheim/valheim_server_Data/MonoBleedingEdge/etc'
Preloaded 'libsteam_api.so'
Initialize engine version: 2019.4.16f1 (e05b6e02d63e)
[Subsystems] Discovering subsystems at path /opt/valheim/valheim_server_Data/UnitySubsystems
Forcing GfxDevice: Null
...
2021-02-15 07:31:41,070 INFO success: valheim-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
valheim-server: ERROR (not running)
valheim-server: started
02/15/2021 07:31:50: Initializing world generator seed: ( 0 )   menu:True  worldgen version:1
...
02/15/2021 07:31:52: Remaining mountains:68
...
02/15/2021 07:31:57: Removing 1225882809
02/15/2021 07:31:57: Removing 404029124
02/15/2021 07:31:57: Audioman already exist, destroying self
Unloading 490 unused Assets to reduce memory usage. Loaded Objects now: 86244.
Total: 69.662500 ms (FindLiveObjects: 4.257700 ms CreateObjectMapping: 3.285200 ms MarkObjects: 60.131100 ms  DeleteObjects: 1.984400 ms)
02/15/2021 07:32:01: Zonesystem Start 233
02/15/2021 07:32:01: DungeonDB Start 233
02/15/2021 07:42:02:  Connections 0 ZDOS:81  sent:0 recv:0
...
```

after which the updater and some steam related daemon continue to occasionally produce output.

But my server is never listed, nor is it anything other than "not responding" from the steam servers list

---

Some questions:

1. what exactly appears in the server list? Your readme mentions that you should "filter", but should I simply filter by server name? is the SERVER_NAME environment parameter something that valheim uses in its filter?
2. why did DungeonDB take 10 minutes to run? Is this normal? Is typical valheim startup time 10-15 minutes?
3. are there any ports other than 2456-2348 that we need? You can see I opened 27015 when looking at some steam help pages, but that hasn't solved any problems. When I add a server on the steam server page, how does my steam client reach out to that server?

Any help is appreicated
