### ISSUE TITLE
Peer 76561197973359387 has wrong password

### ISSUE THREAD

**Issue by GuerrillaCoder** [lloesche/valheim-server-docker#411]
Whatever I do I am unable to load my world in dedicated server.

This is my compose:

```yaml
version: "3.7"

services:
  valheim-server:
    cap_add:
      - sys_nice
    image: ghcr.io/lloesche/valheim-server:latest
    ports:
      - "2456-2457:2456-2457/udp"
    volumes:
      - "/docker/valheim/config:/config"
      - "/docker/valheim/data:/opt/valheim"
    environment:
      - SERVER_NAME:myserver
      - WORLD_NAME:Worldname
      - SERVER_PASS:mypass
    restart: always
    stop_grace_period: 2m
```

I have uploaded my world file to /docker/valheim/data/worlds and set worldname to the name of db file without extension.

What have I done wrong?  It always says wrong password.  It seems to be connecting fine because I can see the message in docker console:

> Peer 76561197973359387 has wrong password
