### ISSUE TITLE
Server does not save world progress.

### ISSUE THREAD

**Issue by UponABlackStar** [lloesche/valheim-server-docker#492]
**Expected Behaviour**

Game progress until the latest restart is loaded.

**Actual Behaviour**

Server resets the world progress to before the latest update. No progress can be made.

**Docker-Compose:**
```
version: "3"

services:
  valheim-myserver:
    container_name: valheim-myserver
    image: ghcr.io/lloesche/valheim-server:latest
    cap_add:
      - sys_nice
    volumes:
      - valheim-myserver-config:/config
      - valheim-myserver-world:/config/worlds_local
      - valheim-myserver-data:/opt/valheim
      - valheim-myserver-backups:/config/backups
      - ./plugins:/config/bepinex/plugins
      - ./plugins-configs:/config/bepinex
    ports:
      - "25568:25568/udp"
    env_file:
      - ./valheim.env
    restart: always
    stop_grace_period: 2m

volumes:
    valheim-myserver-data:
        name: valheim-myserver-data
        external: false
    valheim-myserver-config:
        name: valheim-myserver-config
        external: false
    # These volumes are created manually. That is why they are marked as external
    valheim-myserver-world:
        name: valheim-myserver-world
        external: true
    valheim-myserver-backups:
        name: valheim-myserver-backups
        external: true
```

**valheim.env**
```
SERVER_NAME=My Server
WORLD_NAME=My_World
SERVER_PASS=***************************
SERVER_PORT=25568
SERVER_PUBLIC=false
ADMINLIST_IDS=*********************************
BACKUPS_MAX_AGE=30
BACKUPS_CRON=0 5 2-31/2 * *
BEPINEX=true
```
