### ISSUE TITLE
Please provide an example of a compose file of this container running Valheim Plus

### ISSUE THREAD

**Issue by jpcapone** [lloesche/valheim-server-docker#528]
I don't know where else to ask this question but I am looking for an example of a compose file that has valheim plus enabled.   This is what I have so far.
```
version: '3.3'
services:
    valheim-server:
        container_name: valheim-server
        ports:
            - '2456-2457:2456-2457/udp'
        volumes:
            - '/var/lib/docker/volumes/valheim-server/config:/config'
            - '/var/lib/docker/volumes/valheim-server/data:/opt/valheim'
            - '/var/lib/docker/volumes/valheim-server/config/valheimplus:/config/valheimplus'
            - '/var/lib/docker/volumes/valheim-server/config/valheimplus/plugins:/config/valheimplus/plugins'
        environment:
            - 'SERVER_NAME=Valheim'
            - WORLD_NAME=Neotopia
            - SERVER_PASS=MyrtleAvenue
            - SERVER_PUBLIC=false
            - VALHEIM_PLUS=true
        image: /valheim-server
```
My thoughts are that I need this file and path in place /config/valheimplus/valheim_plus.cfg or use environment variables prefixed with VPCFG for configuration of the mod.  
Please let me know if this is the best way to go about this, TIA!!!
