### ISSUE TITLE
Can't connect over WAN, but can connect LAN

### ISSUE THREAD

**Issue by 46620** [lloesche/valheim-server-docker#552]
I've been attempting to set up a server and every time I start the container I can connect using the local IP of the server, but I can't connect using my public IP. 

Running the command `sudo netstat -anpe | grep "2456" | grep "LISTEN"` brings up nothing, but removing the LISTEN grep I get
```
udp        0      0 0.0.0.0:2456            0.0.0.0:*                           0          49466      3497/docker-proxy   
udp6       0      0 :::2456                 :::*                                0          19645      3516/docker-proxy
```

Some info about the setup:
 - Server is running in Docker on Debian host
 - docker-compose was used in and is managed by portainer
 - 2456-2457 are forwarded on my router
 - I tried with different port numbers and had the same issue

docker-compose.yaml
```yml
version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - /opt/games/valheim-server/config:/config
      - /opt/games/valheim-server/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    environment:
      - SERVER_NAME="[server_name]"
      - WORLD_NAME=[world_name]
      - SERVER_PASS=[password]
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    restart: always
    stop_grace_period: 2m
```
