### ISSUE TITLE
Can't access status web server outside of VM

### ISSUE THREAD

**Issue by zhyph** [lloesche/valheim-server-docker#555]
Hello,

I'm trying to use status web server as a way to make my life easier, and just check in my browser if the connection of my server is ok without the need to SSH into the server and checking manually.

Running `curl localhost:80/status.json` inside my VM works just fine.
But trying to fetch it outside, though my external link, just doesn't work.

This is my docker compose

```yaml
version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
      - "80:80/tcp"
    env_file:
      - $HOME/valheim-server/valheim.env
    restart: always
    stop_grace_period: 2m
```
This is my env file
```
SERVER_NAME=server
WORLD_NAME=MyWorld
SERVER_PASS=password
SERVER_PUBLIC=true
VALHEIM_PLUS=true
STATUS_HTTP=true
```
In my cloud service port 80/tcp is already forwarded, what exactly I'm missing?
