### ISSUE TITLE
Can't reach the ports even when no firewall service is activated

### ISSUE THREAD

**Issue by gridhead** [lloesche/valheim-server-docker#564]
Here's the compose configuration I make use of.

```
---
version: "3.3"
services:
  alcpheim.net:
    image: "docker.io/lloesche/valheim-server:latest"
    network_mode: "apexnenv"
    container_name: "alcpheim.net"
    hostname: "alcpheim"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "8192M"
        reservations:
          cpus: "0.50"
          memory: "4096M"
    environment:
      - "PUID=0"
      - "PGID=0"
      - "TZ=Asia/Kolkata"
      - "SERVER_NAME=Valheim Server on Apex Altruism"
      - "SERVER_PORT=2456"
      - "WORLD_NAME=Neotopia"
      - "SERVER_PASS=alcpheim"
      - "SERVER_PUBLIC=true"
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    volumes:
      - "/home/alcphost/datadisk/servbase/alcpheim/config:/config"
      - "/home/alcphost/datadisk/servbase/alcpheim/data:/opt/valheim"
    cap_add:
      - "sys_nice"
    stop_grace_period: "2m"
    restart: "unless-stopped"
```

I am not able to telnet to the ports even when no firewall service is running to block the ports. Needless to say, I cannot connect to the server as well from the game.

Any help would be appreciated.
