### ISSUE TITLE
Valheim_plus.cfg not loaded

### ISSUE THREAD

**Issue by frankbuma** [lloesche/valheim-server-docker#627]
Hi,
i have some issues with valheim plus regarding the config file. The server ist running but the settings which i made in the config file are not loaded (some things like the size of a chest...).
My compose:
```

version: '3'
services:
  valheim:
    image: lloesche/valheim-server
    container_name: valheim
    restart: always
    environment:
      - SERVER_NAME=valheim_buma
      - WORLD_NAME=Augustiner
      - STATUS_HTTP=true
      - SERVER_PUBLIC=true
      - VALHEIM_PLUS=true
      - VALHEIM_PLUS_RELEASE=latest
      - VALHEIM_PLUS_REPO=Grantapher/ValheimPlus
      - BEPINEX=false
      - STEAMCMD_ARGS=validate
      - BACKUPS_MAX_COUNT=0
      - BACKUPS_MAX_AGE=120
      - TZ=CET


    volumes:
      - /srv/dev-disk-by-label-Files/Config/Valheim/valheim-server-config:/config
    ports:
      - 2456-2458:2456-2458/udp
```

What am i doing wrong and how can i get the config loaded again?
I hope you guys can help me

Thanks in advance!
