### ISSUE TITLE
Xbox client unable to connect with crossplay enabled

### ISSUE THREAD

**Issue by kgadberry** [lloesche/valheim-server-docker#629]
I've set up the server using docker and docker-compose and crossplay doesn't appear to work. A friend with an xbox is unable to connect using `PUBLIC_IP:2456`.
Port forwarding has been set up and verified using a PC client with an external IP address to the public address of the server, so I can rule out network configuration issues.
PC clients using Steam are able to connect just fine. No messages are shown in the server log when the xbox client tries to connect.

This is the docker-compose.yml I use to run the server.
```
version: '3.3'
services:
    main:
        container_name: valheim-server
        image: ghcr.io/lloesche/valheim-server
        cap_add:
          - sys_nice
        ports:
            - '2456-2457:2456-2457/udp'
        volumes:
            - '/srv/valheim-server/config:/config'
            - '/srv/valheim-server/data:/opt/valheim'
        environment:
            - SERVER_NAME=TOAST
            - WORLD_NAME=TOAST
            - SERVER_PASS=redacted
            - SERVER_ARGS='-crossplay'
            - UPDATE_IF_IDLE=true
            - RESTART_IF_IDLE=true
            - SERVER_PUBLIC=false
        restart: always
        stop_grace_period: 2m
```
