### ISSUE TITLE
Server keeps shutting down

### ISSUE THREAD

**Issue by shad-lp** [lloesche/valheim-server-docker#635]
Hello,

I'm back from a couple of months break, since mistlands patch.
So yesterday, I tweaked some variables to use the new forked V+ repo :

```
        - VALHEIM_PLUS_RELEASE=latest
        - VALHEIM_PLUS_REPO=Grantapher/ValheimPlus
```

and launched the server, everything ran smoothly for the couple of hours I spent on the game.

Today, I am being disconnected almost every 1-10 minutes, here are the logs :

[https://pastebin.com/Mpiw7yRL](https://pastebin.com/Mpiw7yRL)

The shutting down signal occurs at **2023-06-19T17:17:06.116628367Z**

Here is my compose file for reference :

```
version: '2.1'
services:

   valheim-plus-server:
      image: lloesche/valheim-server
      container_name: valheim
      hostname: valheim
      networks:
         - net-proxy
         - net-notif
      cap_add:
         - CAP_SYS_NICE
      environment:
         # Configuration
         - PUID=1000
         - PGID=1000
         - SERVER_NAME=REDACTED
         - SERVER_PASS=REDACTED
         - SERVER_PORT=2456
         - WORLD_NAME=NoRulez
         - SERVER_PUBLIC=true
         - RESTART_CRON=45 5 * * *
         - RESTART_IF_IDLE=true
         - TZ=Europe/Brussels
         # Permitted IDs (Steam ID)
         - PERMITTEDLIST_IDS=REDACTED
         # Admin IDs (Steam ID)
         - ADMINLIST_IDS=REDACTED
         # Update configuration
         - UPDATE_CRON=30 6 * * *
         - UPDATE_IF_IDLE=true
         # Backups configuration
         - BACKUPS=true
         - BACKUPS_CRON=10 */6 * * *
         - BACKUPS_DIRECTORY=/config/backups
         - BACKUPS_MAX_AGE=5
         - BACKUPS_MAX_COUNT=25
         - BACKUPS_IF_IDLE=false
         - PERMISSIONS_UMASK=022
         # Status
         - STATUS_HTTP=true
         # Supervisord
         - SUPERVISOR_HTTP=true
         - SUPERVISOR_HTTP_PORT=9001
         # Discord
         - DISCORD_WEBHOOK=https://discord.com/api/webhooks/XXX
         ## Bootstrap
         - 'PRE_BOOTSTRAP_HOOK=curl -X POST -d "tag=botValheim&body=Server starting up..." http://apprise-api:8000/notify/apprise'
         ## Listening
         - 'POST_SERVER_LISTENING_HOOK=curl -X POST -d "tag=botValheim&body=Server __READY__..." http://apprise-api:8000/notify/apprise' 
         ## Shutdown
         - 'PRE_SERVER_SHUTDOWN_HOOK=curl -X POST -d "tag=botValheim&body=Shutting down server..." http://apprise-api:8000/notify/apprise'
         ## Restarting
         - 'PRE_RESTART_HOOK=curl -X POST -d "tag=botValheim&body=Restarting server..." http://apprise-api:8000/notify/apprise'
         # Mods
         - VALHEIM_PLUS=true
         - VALHEIM_PLUS_RELEASE=latest
         - VALHEIM_PLUS_REPO=Grantapher/ValheimPlus
         - VPCFG_AdvancedBuildingMode_enabled=true
         - VPCFG_AdvancedEditingMode_enabled=true
         - VPCFG_Building_enabled=true
         - VPCFG_Building_enableAreaRepair=true
         - VPCFG_Camera_enabled=true
         - VPCFG_Camera_cameraFOV=65
         - VPCFG_Chat_enabled=true
         - VPCFG_Chat_outOfRangeShoutsDisplayInChatWindow=true
         - VPCFG_Chat_defaultNormalDistance=7500
         - VPCFG_FireSource_enabled=true
         - VPCFG_FireSource_torches=true
         - VPCFG_FireSource_fires=true
         - VPCFG_Game_enabled=true
         - VPCFG_Game_bigPortalNames=true
         - VPCFG_Hud_enabled
         - VPCFG_Hud_showRequiredItems=true
         - VPCFG_Hud_experienceGainedNotifications=true
         - VPCFG_Hud_displayBowAmmoCounts=2
         - VPCFG_Map_enabled=true
         - VPCFG_Map_shareMapProgression=true
         - VPCFG_Map_preventPlayerFromTurningOffPublicPosition=true
         - VPCFG_Map_shareAllPins=true
         - VPCFG_Map_displayCartsAndBoats=true
         - VPCFG_GridAlignment_enabled=true
         - VPCFG_Items_enabled=true
         - VPCFG_Items_noTeleportPrevention=true      
         # In case of broken update
         #- STEAMCMD_ARGS=-beta default_old
      ports:
         - 2456-2457:2456-2457/udp
         # if not in net-proxy network
         #- 9001:9001/tcp
      volumes:
         - /opt/valheim-live/config:/config
         - /opt/valheim-live/data:/opt/valheim
      labels:
         # watchtower label only monitoring
         - 'com.centurylinklabs.watchtower.enable=true'
      restart: unless-stopped
      
networks:

   net-proxy:
      external: true
      
   net-notif:
      external: true
```

Thanks in advance.
