### ISSUE TITLE
HTTP_STATUS always returns 0 players

### ISSUE THREAD

**Issue by floryn08** [lloesche/valheim-server-docker#663]
Hi!

I'm using this image using the following docker-compose.yaml file:
```
version: '3.9'

services:

  valheim: 
    container_name: valheim
    image: ghcr.io/lloesche/valheim-server:latest
    cap_add:
      - sys_nice
    volumes: 
      - ${VOLUMES_PATH}/game-servers/valheim/config:/config
      - ${VOLUMES_PATH}/game-servers/valheim/data:/opt/valheim
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro
    ports: 
      - "2456-2458:2456-2458/udp"
      - 1234:80
    environment:
      SERVER_NAME: ${SERVER_NAME}
      WORLD_NAME: ${SERVER_NAME}
      SERVER_PASS: ${SERVER_PASSWORD}
      SERVER_PUBLIC: true
      SUPERVISOR_HTTP: false
      STATUS_HTTP: true
      SERVER_ARGS: -crossplay
      ADMINLIST_IDS: ${VALHEIM_ADMINS}
    restart: unless-stopped
```
When I call `/status.json` the response always shows 0 `player_count` even though my friend and I are connected and playing.

Is this a known problem?
