### ISSUE TITLE
Instructions on how to increase the max allocated RAM/CPU

### ISSUE THREAD

**Issue by 15guim** [lloesche/valheim-server-docker#715]
It may seem trivial but after reading the documentation, i do not understant how/if i can increase the allocated RAM/CPU of the image. My issue is that i am running a modded server witch can have up to 8 players simultaneously. We are running on some pretty heavy desync issues and stalls once there are more than 4 players online at once.
I am currently looking into identifying the ressource bottleneck but i still cannot find where to adjust the allocated RAM/CPU.

Thank you

**Comment by Shawak** [comment]
I dont'think there is a limit set on linux. On windows you can set them in the docker desktop app (assuming you are using it).

**Comment by PirateSeal** [comment]
Using docker compose with swarm you may set the reservations and limits of resources 👍🏻

**Comment by lloesche** [comment]
@15guim the reason why this is not explained is because there are so many ways to run a container.

Setting memory and CPU limits for the Valheim server container depends on your container runtime and host environment. The container image itself doesn't impose limits—those are enforced by the runtime, and behavior varies by platform. Some examples:

 **Linux (native Moby/Podman):**  
  By default, containers inherit the full host’s CPU and memory unless explicitly limited via runtime flags (`--memory`, `--cpus`, etc.).  
  Example:  
  ```bash
  docker run --memory="4g" --cpus="2" ...
  ```

 **macOS and Windows (Docker Desktop or Rancher Desktop for example):**  
  Containers run inside a lightweight VM (usually via HyperKit or WSL2). Even if you don't set container-level limits, your VM has a hard ceiling (configured in Docker Desktop settings). So if your VM is limited to 4 CPUs and 8GB RAM, that’s the *true* maximum available to all containers, regardless of flags.

 **docker-compose:**  
  Limits can be set per service:
  ```yaml
  services:
    valheim:
      image: lloesche/valheim-server
      deploy:
        resources:
          limits:
            cpus: '2.0'
            memory: 4g
  ```
  *Note:* `deploy.resources` only applies when using Swarm mode. For non-Swarm setups, use `mem_limit` and `cpus` instead, but these are legacy and not supported in all Compose versions.

 **Kubernetes:**  
  Use `resources.requests` and `resources.limits` to define both guaranteed and maximum resource usage.  
  ```yaml
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
  ```

On NAS and other appliance systems each manufacturer has their own way of defining limits, often via the WebUI.

So it really depends on how you run the container and is best to consult your container runtime documentation. There's no general answer.
