### ISSUE TITLE
stop_grace_period missing unit in duration "120"???

### ISSUE THREAD

**Issue by TheQueas** [lloesche/valheim-server-docker#746]
I am trying to get this up and running.  I'm using the following docker compose file on Ubuntu:

```
services:
    valheim:
        container_name: valheim-server
        image: lloesche/valheim-server
        cap_add:
            - sys_nice
        ports:
            - "2456-2457:2456-2457/udp"
        volumes:
            - /home/dr-cunt-phd/GameServers/Valheim/config:/config
            - /home/dr-cunt-phd/GameServers/Valheim/data:/opt/valheim
        environment:
            - SERVER_NAME="Need More Wood"
            - WORLD_NAME=#####
            - SERVER_PASS=#####
            - SERVER_ARGS="-crossplay"
        stop_grace_period: "120s"
        restart: always
```

No matter what I do I get the error:

> error decoding 'services[valheim-server].stop_grace_period': time: missing unit in duration "120"

Even if I fully remove the `stop_grace_period: "120s"` I still get that error message.  I've tried changing it to just "120".  I've tried with and without quotation marks.  I saw a docker compose example for QNAP NAS that had `stop_grace_period: 2m`, so I tried that.  I get the exact same error message no matter what, and I'm fully at a loss...  help please!
